<div style="font-family: arial; font-size: 11px">

<h3>TÉRMINOS Y CONDICIONES GENERALES DE USO DEL SITIO</h3>

Los presentes Términos y Condiciones Generales de Uso (en adelante, los “Términos y Condiciones”) regulan el acceso y utilización, por parte del Usuario (conforme se define más adelante), de la página web www.gibeet.com  (en adelante, “la Página Web” o “gibeet”), así como la contratación de productos y servicios a través de la misma.
La Página Web es propiedad de Gibeet. 
Cualquier persona que desee acceder y/o usar la Página Web deberá sujetarse a estos Términos y Condiciones
<br/><br/><br/>
<h3>CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES Y LOS PARTICULARES QUE LE RESULTAREN APLICABLES, LOS CUALES TIENEN CARÁCTER DE OBLIGATORIOS Y VINCULANTES, DEBERÁ ABSTENERSE DE UTILIZAR LA PÁGINA WEB Y/ O CUALQUIER OTRO SERVICIO DE LA COMPAÑÍA.</h3>

El Usuario deberá leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones y demás documentos incorporados a éstos por referencia, previo a su registro como Usuario de Gibeet.<br/>

<h3>A. Capacidad</h3>

Por medio de la aceptación de los presentes Términos y Condiciones, el Usuario declara:<br><br>

    Que ha leído y comprende lo expuesto en el presente instrumento.<br>
    Que es una persona con capacidad suficiente para contratar conforme a la legislación de su país, con el fin de dar plena validez, eficacia y utilidad práctica a todas y cada una de las estipulaciones de los presentes Términos y Condiciones.<br/>
    Que asume todas las obligaciones aquí dispuestas.<br>

El mero hecho de la navegación y/o utilización de la Página Web atribuye a quien la realice la condición de Usuario de la misma (en adelante, “el “Usuario”) e implica la aceptación de estos Términos y Condiciones en todas y cada una de sus partes. En consecuencia, no podrán utilizar los servicios de la Página Web, las personas que no tengan capacidad para contratar, los menores de edad y/o quienes hayan sido suspendidos o inhabilitados por la Compañía y/o el Operador Local para utilizar la Página Web.<br>

<h3>B. Modificaciones</h3>

El Usuario deberá leer atenta y comprensivamente los presentes Términos y Condiciones cada vez que acceda a la Página Web, ya que ambos pueden sufrir modificaciones.<br/>
La Compañía se reserva el derecho de modificar, a su sola discreción, los Términos y Condiciones en cualquier momento, o suspender, cambiar o terminar el Servicio, lo cual se publicará oportunamente en la Página Web. Toda modificación será comunicada con una antelación de 10 (diez) días a su entrada en vigencia. En caso de no estar de acuerdo con dichas modificaciones, el Usuario deberá comunicar vía e-mail a la casilla contacto@gibeet.com si no acepta las mismas; en ese caso quedará disuelto el vínculo contractual y será inhabilitado como Usuario. Vencido este plazo, se considerará que el Usuario acepta los nuevos Términos y Condiciones, los que regirán la relación contractual a partir de dicho momento.<br/>
La Compañía se reserva el derecho de realizar, en cualquier momento y sin necesidad de preaviso, cualquier modificación o actualización de sus contenidos y servicios en general, así como de cuantos elementos integren el diseño y configuración de la Página Web.<br/>

<h3>C. Condiciones de Uso</h3>

1. Acceso a la Página Web.<br/>
El acceso a la Página Web es gratuito, salvo en lo relativo al coste de la conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso contratado (ISP) por el Usuario, que estará a su exclusivo cargo.<br/>

2. Necesidad de Registro<br/>
Por regla general, para el acceso a los contenidos de la Página Web no será necesario el registro del Usuario. No obstante ello, la utilización de determinados servicios estará condicionada al registro previo del Usuario, quien deberá completar todos los campos del formulario de inscripción con datos válidos (en adelante el “Usuario Registrado”). Quien aspire a convertirse en Usuario Registrado deberá verificar que la información que pone a disposición de Gibeet a fin de registrarse en la Página Web sea exacta, precisa y verdadera (en adelante los “Datos Personales”); asimismo asumirá el compromiso de actualizar los Datos Personales cada vez que los mismos sufran modificaciones. La Compañía y/o el Operador Local podrá utilizar diversos medios para identificar a los Usuarios Registrados, pero la Compañía y/o el Operador Local no se responsabiliza por la certeza de los Datos Personales que sus Usuarios Registrados pongan a su disposición. Los Usuarios Registrados garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los Datos Personales puestos a disposición de la Compañía y/ o el Operador Local.<br/>

El Usuario Registrado podrá registrarse como Usuario ONG (en adelante el “Usuario ONG”), que es aquel que se registra con el objeto de subir, dar de alta, incorporar y/o ingresar una ONG (en adelante un “ONG”), mediante los procedimientos, mecanismos y con pleno respeto a los Términos y Condiciones Particulares para Usuarios Empresa , que resulten aplicables por la relación contractual que cada Usuario ONG celebre con el Operador Local que por jurisdicción le corresponda, y que se encontrarán publicados en el sitio web que administre el Operador Local correspondiente.<br/>

Asimismo, el Usuario Registrado podrá registrarse como Usuario Colaborador (en adelante el “Usuario Colaborador”), que es aquel que se registra para estar habilitado y tener la posibilidad de realizar contribuciones (en adelante los “Contribuciones”) a los contenidos publicados por los Usuarios ONG.<br/>
Los Términos y Condiciones serán de aplicación tanto para los Usuarios como para los Usuarios Registrados, no obstante ello, la relación con estos últimos se regirá en forma particular por los Términos y Condiciones Particulares que les resulten aplicables.<br/>

3. Obligación de mantener actualizados los Datos Personales.<br/>
Los Datos Personales introducidos por todo Usuario Registrado en la Página Web, deberán ser exactos, actuales y veraces en todo momento. La Compañía y/o el Operador Local que corresponda, se reservan el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, y de suspender temporal y/o definitivamente a aquellos Usuarios Registrados cuyos datos no hayan podido ser confirmados. La baja o inhabilitación de un Usuario Registrado implicará la baja de todos los proyectos que hubiere publicado, sin que ello genere derecho a resarcimiento o indemnización alguna.<br/>

4. Acceso a la cuenta personal y obligación de confidencialidad de la Clave de Seguridad.<br/>
Para transformarse en Usuario Registrado, el Usuario tendrá acceso a una cuenta personal ("Cuenta") mediante el ingreso de su apodo o nombre de usuario y clave de seguridad personal elegida ("Clave de Seguridad"). Esta Clave de Seguridad es personal e intransferible. El Usuario Registrado se obliga a mantener en estricta confidencialidad su Clave de Seguridad. El Usuario Registrado será, en todo caso, responsable por todo daño, perjuicio, lesión o detrimento que del incumplimiento de esta obligación de confidencialidad se genere por cualquier causa.<br/>
La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario Registrado registre o posea más de una Cuenta. En caso que la Compañía y/o el Operador Local que corresponda, detecte distintas Cuentas que contengan datos coincidentes o relacionados, podrá cancelarlas, suspenderlas o inhabilitarlas, a su sola discreción, siendo el mismo motivo suficiente para dar de baja al Usuario Registrado, incluso en su primer Cuenta. El Usuario Registrado será responsable por todas las operaciones efectuadas desde su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del Usuario y cuya confidencialidad es de su exclusiva responsabilidad. El Usuario Registrado se compromete a notificar a la Compañía y al Operador Local que corresponda según el caso, en forma inmediata y por medio idóneo, fehaciente, eficiente y eficaz, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se encuentra prohibida la venta, cesión, transferencia o transmisión de la Cuenta bajo cualquier título, ya sea oneroso o gratuito.<br/>
La Compañía y/o el Operador Local que corresponda, se reserva el derecho de rechazar cualquier solicitud de registro o de cancelar un registro previamente aceptado, cuando a su sola discreción considere que no se ha dado cumplimiento a la totalidad de las pautas establecidas en los Términos y Condiciones o en los Terminos y Condiciones Particulares para Usuarios ONG y/ o para Usuarios Colaboradores, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere derecho a indemnización o resarcimiento alguno a favor del Usuario Registrado alcanzado por dicha decisión.<br/>

5. Normas generales de utilización de la Página Web.<br/>
Los servicios ofrecidos en la Página Web se dirigen exclusivamente, a personas mayores edad.<br/>
El Usuario y/o el Usuario Registrado, manifiesta, garantiza y declara que tiene la edad legal para formalizar un contrato vinculante, plenamente válido y eficaz, y que toda la información de registro que presenta es exacta, veraz y actualizada.<br/>
La Compañía y/o el Operador Local que corresponda, se reservan el derecho a terminar la Cuenta de aquellos Usuarios Registrados, cuya mayoría de edad resulte dudosa.<br/>
El Usuario y/o el Usuario Registrado, se obliga a utilizar la Página Web y todo su contenido y servicios conforme a lo establecido en la ley, la moral, el orden público, los presentes Términos y Condiciones, y los Terminos y Condiciones Particulares que en cada caso resulten aplicables. Asimismo, se obliga a hacer un uso adecuado de los servicios y/o contenidos de la Página Web y a no emplearlos para realizar actividades ilícitas o constitutivas de delito, que atenten contra los derechos de terceros y/o que infrinjan la regulación sobre propiedad intelectual e industrial, o cualesquiera otras normas del ordenamiento jurídico que puedan resultar aplicables y, en especial, el principio de buena fe que obliga a actuar leal, correcta y honestamente tanto en los tratos preliminares, celebración y ejecución de todo contrato. Como consecuencia de lo anterior, el Usuario se obliga a no difundir, transmitir, introducir y poner a disposición de terceros, cualquier tipo de material e información (datos, contenidos, mensajes, dibujos, archivos de sonido e imagen, fotografías, software, etc.) que sean contrarios a la ley, la moral, el orden público, los presentes Términos y Condiciones, y los Términos y Condiciones Particulares que resulten aplicables.<br/>
A título meramente enunciativo, y en ningún caso limitativo, taxativo o excluyente, el Usuario y/o el Usuario Registrado, se compromete a:<br/><br/>

    (a) No introducir o difundir contenidos o propaganda de carácter racista, xenófobo o, en general, discriminatorio, pornográfico, de apología del terrorismo o que atenten, vulneren o pudieren atentar o vulnerar los derechos humanos.<br/>
    (b) No introducir o difundir en la red programas de datos (virus y/o software nocivos) susceptibles de provocar daños en los sistemas informáticos de Gibeet, sus proveedores, terceros o, en general, cualquier usuario de la red Internet.<br/>
    (c) No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que atente contra los derechos fundamentales y las libertades públicas reconocidos constitucionalmente y en los tratados internacionales.<br/>
    (d) No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que constituya publicidad ilícita o desleal.<br/>
    (e) No transmitir publicidad no solicitada o autorizada, material publicitario, "correo basura", "cartas en cadena", "estructuras piramidales", o cualquier otra forma de solicitación, excepto en aquellas áreas (tales como espacios comerciales) que hayan sido exclusivamente concebidas para ello mediante una comunicación expresa de la Compañía y/o del Operador Local que corresponda, comunicada debida y oportunamente en la Página Web.<br/>
    (f) No introducir o difundir cualquier información y contenidos falsos, ambiguos o inexactos de forma que induzca a error a los receptores de la información.<br/>
    (g) No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que suponga una violación de los derechos de propiedad intelectual e industrial, patentes, marcas o copyright que correspondan a la Compañía o a terceros.<br/>
    (h) No difundir, transmitir o poner a disposición de terceros cualquier tipo de información, elemento o contenido que suponga una violación del secreto de las comunicaciones y la legislación de datos de carácter personal y, en general, toda las normas jurídicas que regulen la protección y promoción del respeto a la vida privada e intimidad de las personas y sus familias.<br/><br/>

El Usuario y/o el Usuario Registrado, se obliga a mantener indemne a la Compañía y/o al Operador Local que corresponda, ante cualquier posible reclamación, multa, pena, sanción o indemnización que pueda venir obligada a soportar como consecuencia del incumplimiento por parte del Usuario de cualquiera de las normas de utilización antes indicadas, reservándose, además, la Compañía el derecho a solicitar la indemnización por daños y perjuicios que corresponda. Asimismo, la Compañía y/o el Operador Local que corresponda, se reserva el derecho de anular la Cuenta de aquellos Usuarios Registrados que hagan un uso inapropiado de la Página Web o no respeten las observaciones y prohibiciones previstas por estos Términos y Condiciones, y los Términos y Condiciones Particulares que resulten aplicables en cada caso.<br/><br/>

6. Responsabilidad de Gibeet y/o el Operador Local que corresponda.<br/>
Por cuanto Gibeet y/o el Operador Local que corresponda, sólo pone a disposición de los Usuarios un espacio virtual que permite a los Usuarios ONG poner sus contenidos a disposición de los Usuarios Colaboradores mediante internet:<br/><br/>

    (a) La Compañía y/o el Operador Local que corresponda, no asume ninguna responsabilidad sobre la actualización de la Página Web, en especial, respecto del contenido o información, ni garantiza que la información publicada contenida en la Página Web sea precisa ni completa. Por lo tanto, cada Usuario será responsable de confirmar que la información publicada en la Página Web sea precisa y completa antes de tomar alguna decisión relacionada con cualquier servicio o contenido descrito en la misma.<br/>
    (b) El acceso del Usuario a la Página Web no implica para la Compañía y/o el Operador Local que corresponda, la obligación de informar, controlar o, actuación alguna referente a la ausencia o presencia de virus, gusanos o cualquier otro elemento informático dañino. Los Usuarios no podrán imputarle responsabilidad alguna a la Compañía y/o al Operador Local que corresponda, ni exigir indemnización bajo ningún concepto, por los perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en internet.<br/>
    (c) La Compañía y/o el Operador Local que corresponda, no garantiza el acceso y uso continuado e ininterrumpido de la Página Web. La Página Web puede eventualmente no estar disponible debido a dificultades técnicas o fallas de internet, o por cualquier otra circunstancia ajena y no imputable a la Compañía y/o al Operador Local que corresponda; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad. La Compañía y/o el Operador Local que corresponda, no serán responsables por ningún error u omisión contenidos en la Página Web.<br/>
    (d) Corresponde al Usuario, en todo caso, la disponibilidad de herramientas adecuadas para la detección y desinfección de programas informáticos dañinos.<br/>
    (e) La Compañía y/o el Operador Local que corresponda, no se responsabilizan de los daños o perjuicios de cualquier tipo producidos en el Usuario a causa de fallos o desconexiones en las redes de telecomunicaciones que produzcan la suspensión, cancelación o interrupción del     servicio de la Página Web durante la prestación del mismo o con carácter previo.<br/>
    (f) La Compañía y/o el Operador Local que corresponda, no se hacen responsables de la actuación de los Usuarios ONG que cargan sus contenidos en la Página Web. La Compañía y/o el Operador Local que corresponda, no son propietarios de los contenidos publicados, ni los ofrecen en venta.<br/><br/>

7. Contenidos y servicios enlazados a través de la Página Web.<br/>
El servicio de acceso a la Página Web puede incluir dispositivos técnicos de enlace, directorios e incluso instrumentos de búsqueda que permitan al Usuario acceder a otras páginas y portales de Internet (en adelante, “Sitios Enlazados”). En estos casos, la Compañía y/o el Operador Local que corresponda, sólo serán responsables de los contenidos y servicios suministrados en los Sitios Enlazados en la medida en que tengan conocimiento efectivo de la ilicitud y no hayan desactivado el enlace con la diligencia debida.<br/>
En el supuesto que el Usuario considere que existe un Sitio Enlazado con contenidos ilícitos o inadecuados podrá comunicárselo a la Compañía y/o el Operador Local que corresponda, sin que     en ningún caso esta comunicación conlleve la obligación de la Compañía y/o del Operador Local que corresponda, de retirar el correspondiente enlace.<br/>
En ningún caso, la existencia de Sitios Enlazados debe presuponer la formalización de acuerdos ni asociación con los responsables o titulares de los mismos, ni la recomendación, promoción o identificación de Gibeet y/o del Operador Local que corresponda, con las manifestaciones, contenidos o servicios proveídos por dichos sitios.<br/>
La Compañía y/o el Operador Local que corresponda, no conocen los contenidos y servicios de los Sitios Enlazados y, por tanto, no se hacen responsables por los daños producidos por la ilicitud, calidad, desactualización, indisponibilidad, error e inutilidad de los contenidos y/o servicios de los Sitios Enlazados ni por cualquier otro daño que no sea directamente imputable a la Compañía y/o al Operador Local que corresponda.<br/>
8. Propiedad intelectual e industrial.<br/>
Todos los contenidos de la Página Web, entendiendo por éstos, a título meramente enunciativo y no taxativo, los textos, fotografías, gráficos, imágenes, iconos, tecnología, software, links y demás contenidos audiovisuales o sonoros, así como su diseño gráfico y códigos fuente, son propiedad intelectual de la Compañía o de terceros, sin que puedan entenderse cedidos al Usuario ninguno de los derechos de explotación reconocidos por la normativa vigente en materia de propiedad intelectual sobre los mismos. Asimismo, las marcas, nombres comerciales o signos distintivos son de propiedad de la Compañía o terceros, sin que pueda entenderse que el acceso a la Página Web atribuye algún derecho sobre los mismos.<br/>
El Usuario declara y garantiza que los contenidos que publique en Gibeet serán únicamente obras originales, creadas por él mismo y que de ningún modo se tratará de copias o reproducciones que violen derechos de propiedad intelectual de terceros. La Compañía y/o el Operador Local que corresponda, podrán cancelar las Cuentas de aquellos Usuarios Registrados que infrinjan cualquier derecho de propiedad intelectual de terceros. La Compañía y/o el Operador Local que corresponda, eliminarán los materiales constitutivos de infracción de conformidad con la normativa vigente de propiedad intelectual e industrial si llega a conocer tal circunstancia.<br/>
La Compañía y/o el Operador Local que corresponda, no poseerán ningún derecho de propiedad sobre el contenido de los proyectos publicados por los Usuarios ONG en la Página Web. Sin embargo, el Usuario ONG otorga a la Compañía y al Operador Local que corresponda, una licencia gratuita y no exclusiva, para todo el ámbito territorial mundial y por el máximo período legal de protección, en virtud de la cual podrán: comunicar públicamente, reproducir, distribuir y transformar el contenido del proyecto para poder desempeñar el servicio.<br/>
Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.<br/><br/>

9. Sanciones<br/>
Sin perjuicio de otras medidas, la Compañía y/o el Operador Local que corresponda, podrán advertir, suspender en forma temporal o inhabilitar definitivamente la cuenta de un Usuario     Registrado, iniciar las acciones que estimen pertinentes y/o suspender la prestación de sus servicios, si; (a) se quebranta o incumple alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones, demás políticas de Gibeet y/o los Terminos y Condiciones Particulares para Usuarios ONG y/o para Usuarios Colaboradores; (b) incumple sus obligaciones como Usuario Registrado; (c) no pudiere verificarse la identidad del Usuario Registrado o cualquier información proporcionada por el mismo fuere errónea; o, (d) si se incurriera a criterio de Gibeet, en conductas o actos dolosos o fraudulentos. En el caso de suspensión o inhabilitación de un Usuario ONG, todos sus Proyectos serán removidos de la Página Web.<br/><br/>

10. Indemnidad<br/>
El Usuario indemnizará y mantendrá indemnes a la Compañía y/o al Operador Local que corresponda, sus filiales, empresas controladas y/o controlantes, directores administradores, representantes y empleados, por cualquier reclamo o demanda de otros Usuarios o de terceros por sus actividades en la Página Web o por el incumplimiento de los Términos y Condiciones, de las demás políticas que se entienden incorporadas al presente instrumento y/o los Terminos y Condiciones Particulares para Usuarios ONG y/o Usuarios Colaboradores, incluyendo los honorarios de abogados en una cantidad razonable.<br/>
D. Nulidad e ineficacia de las cláusulas.<br/>
Si cualquier cláusula incluida en los Términos y Condiciones fuese declarada total o parcialmente, nula o ineficaz en alguna de las jurisdicciones en las que la Compañía tiene presencia, tal nulidad o ineficacia tan sólo afectará a dicha disposición o a la parte de la misma que resulte nula o ineficaz, subsistiendo los Términos y Condiciones en todo lo demás, considerándose tal disposición total o parcialmente no incluida o aplicable en aquella jurisdicción.<br/>

<h3>D. Privacidad de la información.</h3>

Para utilizar los Servicios ofrecidos por Gibeet y/o por el Operador Local que corresponda, los Usuarios que deseen convertirse en Usuarios Registrados, se obligan a facilitar determinados datos de carácter personal prestando su consentimiento para ello. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. Para mayor información sobre la privacidad de los Datos Personales y casos en los que será revelada la información personal, se pueden consultar nuestras Políticas de Privacidad disponibles en las FAQs,<br/><br/>
F. Alcance de los servicios de Gibeet.<br/>
Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre y el Usuario y la Compañía y/o el Operador Local. El Usuario reconoce y acepta que la Compañía y/o el Operador Local que corresponda, no son parte en ninguna operación, ni tienen control alguno sobre la calidad, seguridad o legalidad de los proyectos publicados y la veracidad o exactitud de sus características. La Compañía y/o el Operador Local que corresponda, no pueden asegurar que un Usuario ONG completará el proyecto publicado y entregará las recompensas prometidas ni podrán verificar la identidad o Datos Personales ingresados por los Usuarios Registrados. La Compañía y/o el Operador Local que corresponda, no garantizan la veracidad de la publicidad de terceros que aparezca en el sitio y no será responsable por la correspondencia y/o contratos que el Usuario celebre con dichos terceros o con otros Usuarios.<br/>
G. Preguntas frecuentes.<br/>
Las respuestas a preguntas frecuentes vinculadas a la participación de los Usuarios ONGy/ o de los Usuarios Colaboradores constituyen una descripción genérica que sólo tiene propósitos de información general. Las respuestas a las preguntas frecuentes no hacen referencia a todas las consecuencias legales, impositivas, cambiarias posibles relacionadas con la participación de los Usuarios ONG y/o de los Usuarios Colaboradores en un Proyecto. Las respuestas a las preguntas frecuentes no implican en ningún caso asesoramiento legal o impositivo por parte de Gibeet y/o la Compañía y/o el Operador Local. Estos Términos y Condiciones así como los Términos y Condiciones Particulares que resulten aplicables según el caso, prevalecerán siempre sobre el contenido de la información relativa a Preguntas Frecuentes.<br/>
<br/>

</div>
